// Generated by gencpp from file chuchu_onboard/Int16ArrayHeader.msg
// DO NOT EDIT!


#ifndef CHUCHU_ONBOARD_MESSAGE_INT16ARRAYHEADER_H
#define CHUCHU_ONBOARD_MESSAGE_INT16ARRAYHEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace chuchu_onboard
{
template <class ContainerAllocator>
struct Int16ArrayHeader_
{
  typedef Int16ArrayHeader_<ContainerAllocator> Type;

  Int16ArrayHeader_()
    : header()
    , data()  {
    }
  Int16ArrayHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> const> ConstPtr;

}; // struct Int16ArrayHeader_

typedef ::chuchu_onboard::Int16ArrayHeader_<std::allocator<void> > Int16ArrayHeader;

typedef boost::shared_ptr< ::chuchu_onboard::Int16ArrayHeader > Int16ArrayHeaderPtr;
typedef boost::shared_ptr< ::chuchu_onboard::Int16ArrayHeader const> Int16ArrayHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chuchu_onboard

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'chuchu_onboard': ['/home/grant/ros_ws/src/chuchu_onboard/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc47eb145a11cbe02d6c8cb8248a4099";
  }

  static const char* value(const ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc47eb145a11cbe0ULL;
  static const uint64_t static_value2 = 0x2d6c8cb8248a4099ULL;
};

template<class ContainerAllocator>
struct DataType< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chuchu_onboard/Int16ArrayHeader";
  }

  static const char* value(const ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16[] data\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int16ArrayHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chuchu_onboard::Int16ArrayHeader_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUCHU_ONBOARD_MESSAGE_INT16ARRAYHEADER_H
