// Generated by gencpp from file chuchu_workstation/SetString.msg
// DO NOT EDIT!


#ifndef CHUCHU_WORKSTATION_MESSAGE_SETSTRING_H
#define CHUCHU_WORKSTATION_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <chuchu_workstation/SetStringRequest.h>
#include <chuchu_workstation/SetStringResponse.h>


namespace chuchu_workstation
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace chuchu_workstation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chuchu_workstation::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::chuchu_workstation::SetString&) { return value(); }
};

template<>
struct DataType< ::chuchu_workstation::SetString > {
  static const char* value()
  {
    return "chuchu_workstation/SetString";
  }

  static const char* value(const ::chuchu_workstation::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::chuchu_workstation::SetStringRequest> should match 
// service_traits::MD5Sum< ::chuchu_workstation::SetString > 
template<>
struct MD5Sum< ::chuchu_workstation::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chuchu_workstation::SetString >::value();
  }
  static const char* value(const ::chuchu_workstation::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chuchu_workstation::SetStringRequest> should match 
// service_traits::DataType< ::chuchu_workstation::SetString > 
template<>
struct DataType< ::chuchu_workstation::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::chuchu_workstation::SetString >::value();
  }
  static const char* value(const ::chuchu_workstation::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chuchu_workstation::SetStringResponse> should match 
// service_traits::MD5Sum< ::chuchu_workstation::SetString > 
template<>
struct MD5Sum< ::chuchu_workstation::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chuchu_workstation::SetString >::value();
  }
  static const char* value(const ::chuchu_workstation::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chuchu_workstation::SetStringResponse> should match 
// service_traits::DataType< ::chuchu_workstation::SetString > 
template<>
struct DataType< ::chuchu_workstation::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::chuchu_workstation::SetString >::value();
  }
  static const char* value(const ::chuchu_workstation::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUCHU_WORKSTATION_MESSAGE_SETSTRING_H
